name = "SideKicks"
uuid = "ae7baef6-f8d7-4188-9988-8bf5c4952615"
authors = ["Pablo Marchant "]
version = "0.1.0"

[deps]
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
julia = "1.7.0"
Turing = "0.20.0"
